export enum LocalStorageKeys {

    ONBOARDING_DATA = "LEADFIX_AI_ONBOARDING_DATA",
    ACCESS_TOKEN = "ACCESS_TOKEN_LEADFIX_AI",
    PAYLOAD_DATA = "PAYLOAD_DATA_LEADFIX_AI",
    CURRENT_ORG_ID = "CURRENT_ORG_ID_LEADFIX_AI",
    CURRENT_STEP = "CURRENT_STEP_LEADFIX_AI",
} 
